### ISSUE TITLE
Saving checkpoint with a dataset from the hub failed when WandB is activated

### ISSUE THREAD

**Issue by thomwolf** [huggingface/lerobot#152]
### System Info

```Shell
lerobot main
```

### Information

- [X] One of the scripts in the examples/ folder of LeRobot
- [ ] My own task or dataset (give details below)

### Reproduction

run `python lerobot/scripts/train.py     policy=act     env=aloha     env.task=AlohaInsertion-v0 training.save_freq=10000    dataset_repo_id=lerobot/aloha_sim_insertion_h
uman`

error:
```
INFO 2024-05-08 16:05:43 ts/train.py:357 Checkpoint policy after step 10000
Error executing job with overrides: ['policy=act', 'env=aloha', 'env.task=AlohaInsertion-v0', 'training.save_freq=10000', 'dataset_repo_id=lerobot/aloha_sim_insertion_human']
Traceback (most recent call last):
  File "/home/thomwolf/Documents/Github/lerobot/lerobot/scripts/train.py", line 109, in train_cli
    train(
  File "/home/thomwolf/Documents/Github/lerobot/lerobot/scripts/train.py", line 398, in train
    evaluate_and_checkpoint_if_needed(step + 1)
  File "/home/thomwolf/Documents/Github/lerobot/lerobot/scripts/train.py", line 360, in evaluate_and_checkpoint_if_needed
    logger.save_model(
  File "/home/thomwolf/miniconda3/envs/lerobot/lib/python3.10/site-packages/lerobot/common/logger.py", line 86, in save_model
    artifact = self._wandb.Artifact(
  File "/home/thomwolf/miniconda3/envs/lerobot/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 132, in __init__
    raise ValueError(
ValueError: Artifact name may only contain alphanumeric characters, dashes, underscores, and dots. Invalid name: policy_act-dataset_lerobot/aloha_sim_insertion_human-env_aloha-seed_1000-1000-010000

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

### Expected behavior

No failing.

Need to remove the `/`  in datasets name

**Comment by thomwolf** [comment]
small fix in https://github.com/huggingface/lerobot/commit/f80902b171c0c57c420be849bef2c99a99c6f4a4
