### ISSUE TITLE
--repo-id for mobile aloha datasets

### ISSUE THREAD

**Issue by ramkumarkoppu** [huggingface/lerobot#187]
most of the aloha datasets in https://huggingface.co/lerobot are not available with the --repo-id argument of lerobot/scripts/visualize_dataset.py
for example how to visualise lerobot/aloha_mobile_wash_pan dataset using this script?

**Comment by Cadene** [comment]
I am working on a PR to fix this. I will get back to you as soon as possible

**Comment by Cadene** [comment]
Hey @ramkumarkoppu ,the PR is merged. I made sure to fix this issue. Could you check on our side if the issue is solved? Dont hesitate to message me if you need any help.
Best

**Comment by ramkumarkoppu** [comment]
Hi @Cadene, Tried it after pulling latest but it gives me same error:

`python lerobot/scripts/visualize_dataset.py --repo-id lerobot/aloha_mobile_wash_pan --episode-index 0`

`Traceback (most recent call last):
  File "/home/ram/repos/lerobot/lerobot/scripts/visualize_dataset.py", line 263, in <module>
    main()
  File "/home/ram/repos/lerobot/lerobot/scripts/visualize_dataset.py", line 259, in main
    visualize_dataset(**vars(args))
  File "/home/ram/repos/lerobot/lerobot/scripts/visualize_dataset.py", line 116, in visualize_dataset
    dataset = LeRobotDataset(repo_id)
  File "/home/ram/anaconda3/envs/lerobot/lib/python3.10/site-packages/lerobot/common/datasets/lerobot_dataset.py", line 41, in __init__
    self.hf_dataset = load_hf_dataset(repo_id, version, root, split)
  File "/home/ram/anaconda3/envs/lerobot/lib/python3.10/site-packages/lerobot/common/datasets/utils.py", line 69, in load_hf_dataset
    hf_dataset = load_dataset(repo_id, revision=version, split=split)
  File "/home/ram/anaconda3/envs/lerobot/lib/python3.10/site-packages/datasets/load.py", line 2587, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/ram/anaconda3/envs/lerobot/lib/python3.10/site-packages/datasets/load.py", line 2259, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/ram/anaconda3/envs/lerobot/lib/python3.10/site-packages/datasets/load.py", line 1904, in dataset_module_factory
    raise e1 from None
  File "/home/ram/anaconda3/envs/lerobot/lib/python3.10/site-packages/datasets/load.py", line 1846, in dataset_module_factory
    raise DatasetNotFoundError(msg + f" at revision '{revision}'" if revision else msg)
datasets.exceptions.DatasetNotFoundError: Dataset 'lerobot/aloha_mobile_wash_pan' doesn't exist on the Hub or cannot be accessed at revision 'v1.3'
`

is it the expected way of visualising this dataset?

**Comment by Cadene** [comment]
@ramkumarkoppu In this error message I see revision v1.3, but the revision v1.4 is now selected automatically on master.
This could mean that you didnt install the latest version or you didnt checkout master or rebased on master.

Try this:
```bash
git fetch origin master
git checkout origin/master
python lerobot/scripts/visualize_dataset.py --repo-id lerobot/aloha_mobile_wash_pan --episode-index 0
```

**Comment by ramkumarkoppu** [comment]
Hi @Cadene: Sorry for the late reply, it worked 
<img width="953" alt="image" src="https://github.com/huggingface/lerobot/assets/30557120/795a13e4-7174-4e56-a89c-993724913111">
after pulling latest, I forgot to run `pip install .` again in my environment to update my python packages versions.
