### ISSUE TITLE
Cannot read the training arrow datafile

### ISSUE THREAD

**Issue by kandeng** [huggingface/lerobot#258]
### System Info

```Shell
- `lerobot` version: unknown
- Platform: macOS-12.2.1-arm64-arm-64bit
- Python version: 3.12.3
- Huggingface_hub version: N/A
- Dataset version: N/A
- Numpy version: 1.26.4
- PyTorch version (GPU?): N/A 
- Cuda version: N/A
- Using GPU in script?: No
```

### Information

- [X] One of the scripts in the examples/ folder of LeRobot
- [ ] My own task or dataset (give details below)

### Reproduction

Did we miss any instruction? Anyway, please give us a hint when convenient. 

We tried to look into the content of a training datafile, e.g. tests/data/lerobot/aloha_sim_insertion_human/train/data-00000-of-00001.arrow

We wrote a simple python code as the following,

~~~
import numpy as np
import pyarrow as pa

arrow_file = "data-00000-of-00001.arrow"
print(f" >> Arrow file: {arrow_file} \n\n")

with pa.memory_map(arrow_file, 'r') as source:
    loaded_arrays = pa.ipc.open_file(source).read_all()

arr = loaded_arrays[0]
print(f"{arr[0]} .. {arr[-1]}")
~~~

But when running this code, it complained that it is not an arrow file. 

~~~
$ python3 test_load_arrow.py
 >> Arrow file: data-00000-of-00001.arrow


Traceback (most recent call last):
  File "/Users/dengkan/Projects/lerobot/tests/test_load_arrow.py", line 10, in <module>
    loaded_arrays = pa.ipc.open_file(source).read_all()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/pyarrow/ipc.py", line 234, in open_file
    return RecordBatchFileReader(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/pyarrow/ipc.py", line 110, in __init__
    self._open(source, footer_offset=footer_offset,
  File "pyarrow/ipc.pxi", line 1085, in pyarrow.lib._RecordBatchFileReader._open
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Not an Arrow file
~~~

Many thanks!

### Expected behavior

Expect the result is something like the following,

~~~
observation.images.top  \
0  {'path': 'videos/observation.images.top_episod...

observation.state  \
0  [0.0, -0.96, 1.16, 0.0, -0.3, 0.0, 0.0, 0.0, -...

action  episode_index  \
0  [-0.012271847, -0.9096506, 1.1596895, -0.00613...              0

frame_index  timestamp  next.done  index
0            0       0.00      False      0
~~~

**Comment by kandeng** [comment]
The bug is fixed, we should use RecordBatchStreamReader, rather than ipc,

The correct code is, 

~~~
import numpy as np
import pyarrow as pa

arrow_file = "data-00000-of-00001.arrow"
print(f" >> Arrow file: {arrow_file} \n\n")

with pa.memory_map(arrow_file, 'r') as source:
    # loaded_arrays = pa.ipc.open_file(source).read_all()
    loaded_arrays = pa.RecordBatchStreamReader(source).read_all()

arr = loaded_arrays[0]
print(f"{arr[0]} .. {arr[-1]}")
~~~

The execution result is, 

~~~
$ python3 test_load_arrow.py
 >> Arrow file: data-00000-of-00001.arrow


[('path', 'videos/observation.images.top_episode_000000.mp4'), ('timestamp', 0.0)] .. [('path', 'videos/observation.images.top_episode_000000.mp4'), ('timestamp', 9.979999542236328)]
~~~

**Comment by kandeng** [comment]
The bug is fixed, we should use RecordBatchStreamReader, rather than ipc,
