### ISSUE TITLE
How to make a custom LeRobotDataset with v2?

### ISSUE THREAD

**Issue by alik-git** [huggingface/lerobot#547]
Hi folks, thanks for the amazing open source work!

I am trying to make a custom dataset to use with the LeRobotDataset format.

The readme says to copy the example scripts here which I've done, and I have a working format script of my own.

https://github.com/huggingface/lerobot/blob/8e7d6970eaf5a64b8af6ec45586d201b8ca9ef16/README.md?plain=1#L323

but when it comes time to create the dataset, the `push_dataset_to_hub.py` uses `LeRobotDataset.from_preloaded` which is no longer supported in [dataset V2](https://github.com/huggingface/lerobot/pull/461)

https://github.com/huggingface/lerobot/blob/8e7d6970eaf5a64b8af6ec45586d201b8ca9ef16/lerobot/scripts/push_dataset_to_hub.py#L216

So I'm just wondering what the proper way of loading your own custom local dataset is? 

Thank you in advance for your help!

**Comment by alik-git** [comment]
okay so I've found a work around for now. I initialize an empty dataset and add the frames to it, and then I can load it after calling dataset.consolidate(). If this is a proper way to do it, pls lmk and I'll make a PR with updates to the docs. 

Otherwise please let me know what the right way to do this is. Thank you! I'll update this issue with my code once I've cleaned it up.

**Comment by Robert-hua** [comment]
I encountered the same issue.

**Comment by taochenshh** [comment]
@aliberts i also got the same issue, the documentation on how to generate custom dataset is not up to date now (the code doesn't run anymore). could you please up the instruction and relevant scripts for custom dataset generation? thanks

**Comment by aliberts** [comment]
Hey there,
Yes, all the `push_to_hub` script are deprecated in favor of scripts in [`examples/port_datasets`](https://github.com/huggingface/lerobot/tree/main/examples/port_datasets) (just one for now).

Basically, you need to create a new empty dataset using `LeRobotDataset.create()`, then add individual frames using `add_frame()`, then save the added frames into an episode using `save_episode()` (which actually saves data).
Then at the end you need to call the `consolidate()` method to handle a few more things (we will try to get rid of this step in future iterations) before finally calling the `push_to_hub()` method.

You can find more info about the changes of this new api in the PR ([#461](https://github.com/huggingface/lerobot/pull/461))

We will remove `push_to_hub.py` scripts in the future after adding more equivalent scripts like the one mentioned above in the examples section. Hope this helps!

**Comment by aliberts** [comment]
Will update the Readme soon!

**Comment by tlpss** [comment]
@aliberts, I stumbled upon this problem and could not find it in the readme? Could you make it more explicit?

**Comment by AbdElrahmanMostafaRifaat1432** [comment]
can anybody give us the code to to do that with a static aloha dataset format

**Comment by Wonder1905** [comment]
I've followed:
https://github.com/huggingface/lerobot/blob/main/examples/port_datasets/pusht_zarr.py

But this is extremely memory intensive, using every memory trick I know didnt help it to finish single episode.
Maybe I dont understand whats going "under the hood" but holding a dataset object, that keeps getting multiple frames seems a bit crazy. But maybe Im missing something and I'll be happy for some help here.

**Comment by tlpss** [comment]
@AbdElrahmanMostafaRifaat1432, I have not used the aloha format but I created a [script](https://github.com/tlpss/lerobot/blob/dp_zarr_dataset/examples/port_datasets/dp_3d_zarr.py)  to convert datasets using the format from the diffusion policy codebase. THe process for the aloha format will be very similar, I believe.

**Comment by AbdElrahmanMostafaRifaat1432** [comment]
@tlpss 
I really appreciate your response but I have found an easier solution, I took the script used by openpi to push aloha dataset   

you can find it here: [convert_aloha_to_lerobot](https://github.com/PhysicalIntelligence/openpi/blob/main/examples/aloha_real/convert_aloha_data_to_lerobot.py)

I wonder if there is a solution to convert data immediately locally instead of pushing it to hugging face and taking it again from hugging face.
this would help me a lot actually

**Comment by tlpss** [comment]
@AbdElrahmanMostafaRifaat1432, that is convenient!


> I wonder if there is a solution to convert data immediately locally instead of pushing it to hugging face and taking it again from hugging face.

If you set [this](https://github.com/Physical-Intelligence/openpi/blob/80d346ea0d64fd92f663c705b687bd5fc4bb96a0/examples/aloha_real/convert_aloha_data_to_lerobot.py#L236)  variable to False, the dataset will only be stored locally.  Don't forget to set the `LEROBOT_HOME` env variable to the dir where you want to store the dataset.

**Comment by AbdElrahmanMostafaRifaat1432** [comment]
@tlpss thanks for your response

but the problem is actually when I train the model it cannot see my local files where the data is stored

when I use the following script 
python lerobot/scripts/train.py --policy.type=pi0 --dataset.repo_id=Abdorifaat/basket --dataset.local_files_only=true

I have the following error

INFO 2025-02-10 03:21:53 ts/train.py:206 Creating dataset
Traceback (most recent call last):
  File "/home/SSD1/abdelrahman_refaat/.conda/envs/rifaatrobotics/lib/python3.10/site-packages/lerobot/lerobot/scripts/train.py", line 565, in <module>
    train()
  File "/home/SSD1/abdelrahman_refaat/.conda/envs/rifaatrobotics/lib/python3.10/site-packages/lerobot/lerobot/configs/parser.py", line 120, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/home/SSD1/abdelrahman_refaat/.conda/envs/rifaatrobotics/lib/python3.10/site-packages/lerobot/lerobot/scripts/train.py", line 207, in train
    offline_dataset = make_dataset(cfg)
  File "/home/SSD1/abdelrahman_refaat/.conda/envs/rifaatrobotics/lib/python3.10/site-packages/lerobot/lerobot/common/datasets/factory.py", line 86, in make_dataset
    ds_meta = LeRobotDatasetMetadata(cfg.dataset.repo_id, local_files_only=cfg.dataset.local_files_only,root=cfg.dataset.root_dir)
  File "/home/SSD1/abdelrahman_refaat/.conda/envs/rifaatrobotics/lib/python3.10/site-packages/lerobot/lerobot/common/datasets/lerobot_dataset.py", line 87, in __init__
    self.pull_from_repo(allow_patterns="meta/")
  File "/home/SSD1/abdelrahman_refaat/.conda/envs/rifaatrobotics/lib/python3.10/site-packages/lerobot/lerobot/common/datasets/lerobot_dataset.py", line 98, in pull_from_repo
    snapshot_download(
  File "/home/SSD1/abdelrahman_refaat/.conda/envs/rifaatrobotics/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/SSD1/abdelrahman_refaat/.conda/envs/rifaatrobotics/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 216, in snapshot_download
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input.

could you try it please and tell me how to solve it

**Comment by Tavish9** [comment]
Hi all, I have release a script about the conversion from OpenX(RLDS) to LeRobotV2.1, see [this](https://github.com/Tavish9/openx2lerobot).

You can easily modify the code to make a custom LeRobotDataset, by just changing the source and everything is done. 🥳
